import { Opportunity } from '../types'

export const mockOpportunities: Opportunity[] = [
  {
    id: 'o1', companyId: 'c1', contactId: 'ct1',
    stage: 'Warm', priority: 'high', inPipeline: true,
    dealValue: 48000,
    nextStep: 'Send revised proposal with updated pricing',
    followUpDate: '2026-04-02',
    lastInteraction: '2026-03-24',
    tags: ['enterprise', 'high-intent'],
    notes: 'Elena responded positively to the demo. Main concern is onboarding timeline.',
  },
  {
    id: 'o2', companyId: 'c2', contactId: 'ct2',
    stage: 'Meeting Booked', priority: 'high', inPipeline: true,
    dealValue: 120000,
    nextStep: 'Discovery call Thursday 2pm',
    followUpDate: '2026-03-27',
    lastInteraction: '2026-03-22',
    tags: ['warm', 'decision-maker-engaged'],
    notes: 'Marcus connected via LinkedIn. They are evaluating 3 vendors.',
  },
  {
    id: 'o3', companyId: 'c3', contactId: 'ct3',
    stage: 'Contacted', priority: 'medium', inPipeline: true,
    dealValue: 24000,
    nextStep: 'Follow up on email sent last week',
    followUpDate: '2026-03-28',
    lastInteraction: '2026-03-18',
    tags: ['cold'],
    notes: 'No reply yet. Sent intro email with case study.',
  },
  {
    id: 'o4', companyId: 'c4', contactId: 'ct4',
    stage: 'Proposal Sent', priority: 'critical', inPipeline: true,
    dealValue: 75000,
    nextStep: 'Check if proposal was reviewed',
    followUpDate: '2026-03-26',
    lastInteraction: '2026-03-20',
    tags: ['proposal-sent'],
    notes: 'Priya asked for a 12-month contract option. Board decision next week.',
  },
  {
    id: 'o5', companyId: 'c5', contactId: 'ct5',
    stage: 'New', priority: 'low', inPipeline: false,
    dealValue: 18000,
    nextStep: 'Research company and personalize outreach',
    followUpDate: '2026-04-05',
    lastInteraction: '2026-03-25',
    tags: ['new', 'referral'],
    notes: 'Referred by existing client. No contact made yet.',
  },
  {
    id: 'o6', companyId: 'c6', contactId: 'ct6',
    stage: 'Negotiation', priority: 'high', inPipeline: true,
    dealValue: 200000,
    nextStep: 'Legal review of contract terms',
    followUpDate: '2026-03-30',
    lastInteraction: '2026-03-23',
    tags: ['enterprise', 'slow-moving'],
    notes: 'Ingrid wants custom SLA terms. Legal is involved on their side.',
  },
  {
    id: 'o7', companyId: 'c1', contactId: 'ct1',
    stage: 'Researched', priority: 'medium', inPipeline: false,
    dealValue: 32000,
    nextStep: 'Draft personalized outreach email',
    followUpDate: '2026-04-01',
    lastInteraction: '2026-03-21',
    tags: ['researched'],
    notes: 'Secondary opportunity at Meridian Labs for their EU expansion team.',
  },
]
