import { Task } from '../types'

export const mockTasks: Task[] = [
  {
    id: 't1',
    title: 'Send revised proposal to Elena',
    description: 'Updated pricing with the volume discount she asked about',
    relatedOpportunityId: 'o1',
    relatedCompanyId: 'c1',
    dueDate: '2026-03-26',
    completed: false,
    priority: 'high',
    createdAt: '2026-03-24T10:00:00Z',
  },
  {
    id: 't2',
    title: 'Prepare SOC2 cert and data portability doc',
    description: 'Marcus asked for these during the last call',
    relatedOpportunityId: 'o2',
    relatedCompanyId: 'c2',
    dueDate: '2026-03-27',
    completed: false,
    priority: 'high',
    createdAt: '2026-03-22T15:00:00Z',
  },
  {
    id: 't3',
    title: 'Follow up on intro email to Calloway',
    description: 'Sent case study last week, no reply yet',
    relatedOpportunityId: 'o3',
    relatedCompanyId: 'c3',
    dueDate: '2026-03-28',
    completed: false,
    priority: 'medium',
    createdAt: '2026-03-18T09:00:00Z',
  },
  {
    id: 't4',
    title: 'Check if Sable reviewed the proposal',
    description: 'Priya mentioned board decision next week',
    relatedOpportunityId: 'o4',
    relatedCompanyId: 'c4',
    dueDate: '2026-03-26',
    completed: false,
    priority: 'critical',
    createdAt: '2026-03-20T14:00:00Z',
  },
  {
    id: 't5',
    title: 'Research Fenwick Advisory before outreach',
    description: 'Referred by existing client — personalize the approach',
    relatedOpportunityId: 'o5',
    relatedCompanyId: 'c5',
    dueDate: '2026-04-01',
    completed: false,
    priority: 'low',
    createdAt: '2026-03-25T11:00:00Z',
  },
  {
    id: 't6',
    title: 'Review Orin contract terms with legal',
    description: 'Ingrid wants custom SLA — need legal sign-off',
    relatedOpportunityId: 'o6',
    relatedCompanyId: 'c6',
    dueDate: '2026-03-29',
    completed: false,
    priority: 'high',
    createdAt: '2026-03-23T16:00:00Z',
  },
  {
    id: 't7',
    title: 'Book exec demo for Meridian Labs',
    description: 'Elena wants to show the platform to her leadership team',
    relatedOpportunityId: 'o1',
    relatedCompanyId: 'c1',
    dueDate: '2026-03-25',
    completed: true,
    priority: 'high',
    createdAt: '2026-03-24T10:32:00Z',
  },
  {
    id: 't8',
    title: 'Explore lighter tier for SMB segment',
    description: 'Internal task — losing deals under 10k on pricing',
    dueDate: '2026-04-10',
    completed: false,
    priority: 'medium',
    createdAt: '2026-03-25T09:00:00Z',
  },
]
